# Generated by Django 4.0.4 on 2022-06-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSeguimiento', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('nombreCliente', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('direccionCliente', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('horaLlegadaCrear', models.DateTimeField(auto_now_add=True)),
                ('horaLlegadaActualizar', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_venta',
            },
        ),
    ]
